{
  imports = [
    ./acpid.nix
    ./basePackages.nix
    ./bluetooth.nix
    ./browser
    ./coding.nix
    ./drives.nix
    ./fish.nix
    ./flatpak.nix
    ./gaming.nix
    ./gdm.nix
    ./git.nix
    ./gnome.nix
    ./gnomeServices.nix
    ./gpu.nix
    ./greetd.nix
    ./homePackages.nix
    ./hyprland
    ./kde.nix
    ./kdeConnect.nix
    ./keepassxc.nix
    ./kitty.nix
    ./media.nix
    ./ncspot.nix
    ./nextcloud.nix
    ./oxi
    ./piper.nix
    ./podman.nix
    ./docker.nix
    ./printing.nix
    ./scripts.nix
    ./sddm.nix
    ./sops.nix
    ./starship.nix
    ./stylix.nix
    ./teams.nix
    ./virtualbox.nix
    ./mime.nix
    ./xkb.nix
    ./xone.nix
    ./yazi
  ];
}
