{
  imports = [
    ./acpid.nix
    ./base_packages.nix
    ./bluetooth.nix
    ./coding.nix
    ./drives.nix
    ./firefox.nix
    ./fish.nix
    ./flatpak.nix
    ./gaming.nix
    ./git.nix
    ./gnome_services.nix
    ./gpu.nix
    ./greetd.nix
    ./home_packages.nix
    ./hyprland
    ./kde_connect.nix
    ./keepassxc.nix
    ./layout.nix
    ./media.nix
    ./nextcloud.nix
    ./piper.nix
    ./printing.nix
    ./sops.nix
    ./starship.nix
    ./stylix.nix
    ./teams.nix
    ./virtualbox.nix
    ./xone.nix
    ./yazi
  ];
}
