[manager]
layout = [1, 4, 3]
sort_by = "modified"
sort_sensitive = true
sort_reverse = true
sort_dir_first = true
show_hidden = false
show_symlink = true

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""

[opener]
folder = [
  { run = 'open -R "$@"', orphan = true, display_name = "Reveal in Finder" },
  { run = '$EDITOR "$@"', orphan = true },
]
archive = [{ run = 'unar "$1"', display_name = "Extract here" }]
text = [{ run = '$EDITOR "$@"', orphan = true }]
image = [
  { run = 'imv "$@"', orphan = true, display_name = "Open" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show EXIF" },
]
pdf = [{ run = 'zathura "$@"', orphan = true, display_name = "Open" }]
video = [
  { run = 'mpv "$@"', orphan = true },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
]
audio = [
  { run = 'xdg-open "$@"', orphan = true },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
]
fallback = [
  { run = 'xdg-open "$@"', orphan = true, display_name = "Open" },
  { run = 'xdg-open -R "$@"', orphan = true, display_name = "Reveal in Finder" },
]

[open]
rules = [
  { name = "*/", use = "folder" },

  { mime = "text/*", use = "text" },
  { mime = "image/*", use = "image" },
  { mime = "application/pdf", use = "pdf" },
  { mime = "video/*", use = "video" },
  { mime = "audio/*", use = "audio" },
  { mime = "inode/x-empty", use = "text" },

  { mime = "application/json", use = "text" },
  { mime = "*/javascript", use = "text" },

  { mime = "application/zip", use = "archive" },
  { mime = "application/gzip", use = "archive" },
  { mime = "application/x-tar", use = "archive" },
  { mime = "application/x-bzip", use = "archive" },
  { mime = "application/x-bzip2", use = "archive" },
  { mime = "application/x-7z-compressed", use = "archive" },
  { mime = "application/x-rar", use = "archive" },

  { mime = "*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
  { mime = "text/csv", run = "miller" },
]
