#!/bin/bash

#if [ "$PLAYER_EVENT" = "start" ] || [ "$PLAYER_EVENT" = "change" ];
#then
	trackName=$(playerctl -p spotifyd,%any metadata title)
	artistAndAlbumName=$(playerctl -p spotifyd,%any metadata --format "{{ artist }} ({{ album }})")
  Thumbnail_url=$(playerctl -p spotifyd,%any metadata mpris:artUrl)
  Thumbnail=$(curl "$Thumbnail_url")
	notify-send -u low "$trackName" "$artistAndAlbumName " -i "$Thumbnail"
#fi
