#! /bin/bash

SINK=$(pactl info | grep "Default Sink"| awk -F 'Default Sink: ' ' { print $2 } ')
pactl set-sink-mute $SINK toggle
MUTE=$(pactl list sinks | grep -A 6 "$SINK" | grep "Mute: yes" | tr -d '\t')

if [ "$MUTE" = "Mute: yes" ]; then
  dunstify -a "toggleMute" -r 2 -u low "Muted"
else
  dunstify -a "toggleMute" -r 2 -u low "Unmuted"
fi

