[background]
# path = "/usr/share/backgrounds/greeter.jpg"
fit = "Contain"

[env]
PATH = "/home/dashie/.config/:$HOME/.local/bin:/home/dashie/.cargo/bin:$PATH"
QT_QPA_PLATFORMTHEME = "qt5ct"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Adwaita"
icon_theme_name = "Adwaita"
theme_name = "adw-gtk3"

[commands]
reboot = ["systemctl", "reboot"]
poweroff = ["systemctl", "poweroff"]
