#!/bin/bash

pacfile="$HOME/.config/scripts/pacmanpkg.txt"

save() {
	rm $pacfile
	var=$(pacman -Q)
	echo $var
	if [ "$pacfile" != ' ' ]; then
		touch $pacfile
	fi
	echo "$var" | awk '{ print $1 }' >>$pacfile
}

load() {
	sudo paru -S - <$pacfile
}

if [ "$1" == "-S" ]; then
	sudo pacman -S $2
elif [ "$1" == "-R" ]; then
	sudo pacman -R $2
elif [ "$1" == "save" ]; then
	save
elif [ "$1" == "load" ]; then
	load
fi
