#!/bin/bash
weather=$(cat $HOME/.cache/weather/weather-stat)
weather_count=$(cat $HOME/.cache/weather/weather-stat | wc -c)

if [ "$weather_count" -lt 10 ]; then
	echo $weather;
else 
	echo $(cat $HOME/.cache/weather/weather-stat | cut -c1-6)...
fi
