# by https://github.com/danth/stylix/blob/master/.github/workflows/docs.yml
name: Release
on:
  release:
    types: [created]
jobs:
  build:
    name: Release
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: |
            extra-experimental-features = nix-command flakes pipe-operators
      - name: Set up cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build ISO
        run: nix build github:${{ github.repository }}/${{ github.sha }}#iso --no-write-lock-file
      - name: Prepare ISO for upload
        run: |
          cp -r --dereference --no-preserve=mode,ownership result/ public/
      - name: upload ISO
        uses: softprops/action-gh-release@v1
        with:
          path: path/
